Todo.create(name: "Walk the dog", done: true)
Todo.create(name: "Do homework", done: true)
Todo.create(name: "Visit mum", done: false)
Todo.create(name: "Get shopping", done: true)
Todo.create(name: "Clean", done: false)